kind: PersistentVolume 
apiVersion: v1
metadata:
  name: pv-lykops-sfs-0
  labels:
    type: nfs
    app: pv
    version: v1
  spec:
   capacity:
           storage: 1Gi
   accessModes:
           -ReadWriteMany
   persistentVolumeReclaimPolicy: Recycle
      nfs:
        path: /data
        readOnly: false
